-- treesitter - https://github.com/nvim-treesitter/nvim-treesitter
-- Parser/query management only. Highlighting is handled natively via
-- vim.treesitter.start() in core/autocmds.lua.

return {
    "nvim-treesitter/nvim-treesitter",
    lazy = false,
    build = ":TSUpdate",
    config = function()
        require("nvim-treesitter").setup({
            install_dir = vim.fn.stdpath("data") .. "/site",
        })
        require("nvim-treesitter").install({
            "awk",
            "bash",
            "bitbake",
            "c",
            "cmake",
            "comment",
            "cpp",
            "devicetree",
            "diff",
            "dockerfile",
            "git_config",
            "git_rebase",
            "gitattributes",
            "gitcommit",
            "gitignore",
            "haskell",
            "html",
            "ini",
            "json",
            "jq",
            "kdl",
            "kconfig",
            "latex",
            "lua",
            "make",
            "markdown",
            "markdown_inline",
            "ninja",
            "nginx",
            "objdump",
            "passwd",
            "pem",
            "python",
            "query",
            "regex",
            "rst",
            "rust",
            "ssh_config",
            "toml",
            "vim",
            "vimdoc",
            "wit",
            "xml",
            "yaml",
        })
    end,
}
